### ISSUE TITLE
'RosPack' object has no attribute 'get_custom_cache'

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#170] opened 2015-10-15 16:30 UTC
https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/85478946

```
rostest log file is in /workspace/jsk-ros-pkg/jsk_common/log/rostest-ed647aac93fe-25923.log
install/share/jsk_topic_tools/test/test_topic_buffer_update_rate.test
... logging to /workspace/jsk-ros-pkg/jsk_common/log/rostest-ed647aac93fe-26037.log
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain
    testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest
    config = roslaunch.parent.load_config_default([test_file], None)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 730, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 702, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 666, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 587, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 325, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 137, in _find
    source_path_to_packages = rp.get_custom_cache('source_path_to_packages', {})
AttributeError: 'RosPack' object has no attribute 'get_custom_cache'
install/share/jsk_topic_tools/test/test_topic_buffer_fixed_rate.test
... logging to /workspace/jsk-ros-pkg/jsk_common/log/rostest-ed647aac93fe-26043.log
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain
    testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest
    config = roslaunch.parent.load_config_default([test_file], None)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 730, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 702, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 666, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 587, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 325, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 137, in _find
    source_path_to_packages = rp.get_custom_cache('source_path_to_packages', {})
AttributeError: 'RosPack' object has no attribute 'get_custom_cache'
```

**Comment by garaemon** [comment] 2015-10-15 16:35
related to https://github.com/ros/ros_comm/pull/676 ?

**Comment by wkentaro** [comment] 2015-10-16 12:47
Please restart it, I confirmed `python-rospkg 1.0.37` is released at this time.

**Comment by garaemon** [comment] 2015-10-17 04:45
Still it has the same error.
https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/85464106#L6606

**Comment by wkentaro** [comment] 2015-10-17 04:58
I don't understand why this happen. I also have that test failure at https://github.com/jsk-ros-pkg/jsk_common/pull/1186, and checking why the test failure.

**Comment by wkentaro** [comment] 2015-10-17 06:43
The version of rospkg was 1.0.35, it should be 1.0.37.
`python-rospkg` is dependent package of `ros-$ROS_DIRSTRO-roslaunch`, so  we need to upgrade the dependencies also when apt-get install.

https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/85871416
```
+ pip show rospkg

+ grep '^Version'

+ awk '{print $2}'

The directory '/workspace/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning

1.0.35

```

**Comment by wkentaro** [comment] 2015-10-17 06:48
`apt-get install -f`?

**Comment by wkentaro** [comment] 2015-10-17 07:14
I need to sudo apt-get upgrade [package].

**Comment by k-okada** [comment] 2015-10-17 07:43
Ok I have updated pkg in docker image , please try again

**Comment by wkentaro** [comment] 2015-10-17 08:13
It's fixed. https://github.com/jsk-ros-pkg/jsk_common/pull/1189

**Comment by wkentaro** [comment] 2015-10-17 08:14
Is this problem able to be detected automatically?
Or we will encounter this kind of issue frequently.

**Comment by k-okada** [comment] 2015-10-18 06:57
the jenkins machine uses our custom build docker image which include basic 
ros packages for not to take time for installing ros systems every time, so
if we run apt-get upgrade or uses plane ubuntu docker image, then this 
problem should never happens.
Since official hydro build has been terminated, but we still checking hydro 
on our travis, so we'd better not to depends on latest packages.

--
◉ Kei Okada

**Comment by wkentaro** [comment] 2015-10-18 07:10
> if we run apt-get upgrade 

so should we add `apt-get upgrade` line in `travis.sh`?

> Since official hydro build has been terminated, but we still checking hydro
on our travis, so we'd better not to depends on latest packages.

I think your're right.

**Comment by tiblop** [comment] 2015-10-20 02:10
hello i have the same problem, i have upgraded my ros packages and python-rospkg. The problem is still there. 
I'm not sure what i should do now...? 
thanks

**Comment by wkentaro** [comment] 2015-10-20 02:19
you shoul check the rospkg's version with pip and apt.

apt-cache show pythom-rospkg

and

pip show rospkg

**Comment by tiblop** [comment] 2015-10-20 02:34
they both give Version: 1.0.35
however 
sudo pip install rospkg --upgrade
and 
sudo apt-get upgrade  pythom-rospkg
does change the version to 1.0.37 ..
( i've run apt-get update before )... 
what can I do? 
thanks

**Comment by wkentaro** [comment] 2015-10-20 05:50
rospkg in the version `1.0.37` should not raise this error.
you can run `roslaunch` again.

**Comment by tiblop** [comment] 2015-10-20 05:51
yes i cannot manage to put rospack in 1.0.37.. 
i've tried 
 sudo pip install rospkg --upgrade
 sudo apt-get upgrade python-rospkg
but still 1.0.35

**Comment by wkentaro** [comment] 2015-10-20 05:57
oh, I was mistaken your comment.
please give me below commands' output
```
apt-cache showpkg python-rospkg
apt-cache show python-rospkg

pip search rospkg
pip show rospkg
```

**Comment by tiblop** [comment] 2015-10-20 06:04
apt-cache showpkg python-rospkg
    Package: python-rospkg
    Versions: 
    1.0.35-1 (/var/lib/apt/lists/packages.ros.org_ros_ubuntu_dists_wheezy_main_binary-armhf_Packages.gz)
    Description Language: 
                 File: /var/lib/apt/lists/packages.ros.org_ros_ubuntu_dists_wheezy_main_binary-armhf_Packages.gz
                  MD5: 3ac88cd97e8dbfb36acd72f5165f1f4f


    Reverse Depends: 
      python3-rospkg,python-rospkg
      python-rosinstall-generator,python-rospkg
      python-rosdistro,python-rospkg
      python-rosdep,python-rospkg 1.0.34
      python-jenkins-tools,python-rospkg
    Dependencies: 
    1.0.35-1 - python (2 2.7) python (3 2.8) python:any (2 2.7.1-0ubuntu2) python-yaml (0 (null)) lsb-release (0 (null)) python3-rospkg (0 (null)) 
    Provides: 
    1.0.35-1 - 
    Reverse Provides: 


apt-cache show python-rospkg

    Package: python-rospkg
    Version: 1.0.35-1
    Architecture: all
    Maintainer: Ken Conley <kwc@willowgarage.com>
    Installed-Size: 153
    Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python-yaml, lsb-release
    Conflicts: python3-rospkg
    Priority: optional
    Section: python
    Filename: pool/main/p/python-rospkg/python-rospkg_1.0.35-1_all.deb
    Size: 22656
    SHA256: d26705fc27c6e43ffb42711144be413d169157e7dac0b9040014d9b1482509c8
    SHA1: 040f727449116a8a7225f155fad831bd83805a1d
    MD5sum: e6c45e3425d864213dbc316fad9ffbdf
    Description: ROS package library
     Library for retrieving information about ROS packages and stacks.


pip search rospkg
    /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
    rospkg     - ROS package library
      INSTALLED: 1.0.35
      LATEST:    1.0.37


pip show rospkg

    ---
    Metadata-Version: 1.1
    Name: rospkg
    Version: 1.0.35
    Summary: ROS package library
    Home-page: http://wiki.ros.org/rospkg
    Author: Ken Conley
    Author-email: kwc@willowgarage.com
    License: BSD
    Location: /usr/local/lib/python2.7/dist-packages
    Requires: PyYAML

**Comment by wkentaro** [comment] 2015-10-20 06:07
`1.0.37-1` should be listed in `apt-cache showpkg python-rospkg`.
so it seems that you have some problems in `sudo apt-get update`.

**Comment by tiblop** [comment] 2015-10-20 06:39
what can i do to fix the problem?

**Comment by wkentaro** [comment] 2015-10-20 06:49
No errors or warnings in `sudo apt-get update`?
If so, you should wait for release of `python-rospkg` in your living region.

**Comment by tiblop** [comment] 2015-10-20 07:06
this worked for me : 
sudo easy_install -U rospkg
thanks for helping

**Comment by gmhuili** [comment] 2015-10-24 16:48
I'm facing the same issue with Indigo built from source. How could I upgrade or patch it?

**Comment by wkentaro** [comment] 2015-10-25 02:03
please ask on answers.ros.org.
we are not maintainers of rospkg and roslaunch. 
you can upgrade it by apt-get or pip in most cases. if it fails, your environment is not standard.

**Comment by gmhuili** [comment] 2015-10-25 17:27
OK, Thanks anyway.

**Comment by Marcello-LI** [comment] 2015-10-27 12:57
'pip install rospkg --upgrade' should work.

**Comment by gmhuili** [comment] 2015-10-27 17:29
Yes, this solved the problem. Thanks a lot!

**Comment by wkentaro** [comment] 2015-11-02 12:38
This is fixed by https://github.com/jsk-ros-pkg/jsk_travis/issues/170#issuecomment-148985732.
So please close.

**Closed** 2015-11-02 12:44 UTC
